//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Microsoft Power Platform Tools")]
[assembly: AssemblyDescription("Microsoft Power Platform Tools for Visual Studio")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyProduct("Microsoft Dynamics© CRM")]
[assembly: AssemblyVersion("0.1.9.0")]
[assembly: AssemblyFileVersion("0.1.9.0")]
[assembly: AssemblyInformationalVersion("0.1.0000.1+gd485dc2")]
[assembly: AssemblyCopyright("© 2021 Microsoft Corporation. All rights reserved")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: Guid("adffeca4-16ad-4a64-a61b-66eb090531eb")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

